name: CSPR Java SDK Standard Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      java-repo:
        required: true
        type: string

jobs:
  build:

    name: Java SDK Standard Tests
    runs-on: ubuntu-latest

    steps:

      - name: Print Inputs
        run: |
          echo "java-repo: ${{ inputs.java-repo }}"

      # Checkout the latest Casper Java SDK from their repo ready for a build
      - name: Checkout SDK source code
        uses: actions/checkout@v2
        with:
          repository: casper-network/casper-java-sdk
#          ref: ${{ inputs.java-repo }}
          path: casper-java-sdk

      # JDK environment to build the SDK jar
      - name: Setup SDK Java environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the SDK jar files
      - name: Build SDK JAR
        working-directory: casper-java-sdk
        run: ./gradlew clean build -x test

      # Upload the built SDK jar as a project artifact
      - name: Upload SDK jar to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: casper-java-sdk-jar
          path: |
            casper-java-sdk/build/libs/*.jar

      # Checkout the test platform java code
      - name: Checkout test platform code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Download the SDK jar artifact
      - name: Download casper-java-sdk-jar artifact
        uses: actions/download-artifact@v3
        with:
          name: casper-java-sdk-jar

      # Gradle needs execute permissions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Move the assets to their required folders
      # Run the actual cucumber tests
      - name: Test with cucumber
        run: |
          cd sh && chmod +x docker-copy-assets.sh && ./docker-copy-assets.sh && cd ..              
          ./gradlew clean cucumberCli -DrootLogger.level=OFF

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'reports/*.xml'
          detailed_summary: true
          include_passed: true
          summary: true

