name: Execute SDK Standard Tests

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node build repo'
        required: true
        default: 'release-1.5.5'
      run_java_tests:
        description: 'Run Java SDK Tests'
        required: true
        default: true
        type: boolean
      java_repo:
        description: 'Java Repo'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Execute SDK Tests

    steps:

      - name: Check NCTL Dockerfile
        uses: actions/checkout@v3
      - name: Build NCTL image
        run: docker build --build-arg="GITBRANCH=${{ github.event.inputs.node_version }}" -t stormeye2000/cspr-nctl .
      - name: Start NCTL
        run: docker run --rm -it --name cspr-nctl -d -p 25101:25101 -p 11101:11101 -p 14101:14101 -p 18101:18101 stormeye2000/cspr-nctl

  run-java:

        if: ${{ always() && github.event.inputs.run_java_tests}}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Java SDK Test
            uses: actions/checkout@v1
          - name: Run Test
            uses: ./.github/actions/run-java

