name: Execute SDK Standard Tests

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node build repo'
        required: true
        default: 'release-1.5.5'
      run-java-tests:
        description: 'Run Java SDK Tests'
        required: true
        default: true
        type: boolean
      java-repo:
        description: 'Java Repo'
        required: false
        default: 'main'

jobs:

  build:

    runs-on: ubuntu-latest
    name: Execute SDK Tests

    steps:

      - uses: tyriis/docker-image-tag-exists@v2.0.0
        id: nctl-docker-image-exists
        with:
          registry: docker.io
          repository: stormeye2000/cspr-nctl
          tag: '${{ github.event.inputs.node-version }}'

#      - name: Print Inputs
#        run: |
#          echo "tag: ${{ steps.nctl-docker-image-exists.outputs.tag }}"

      - name: Checkout the dockerfile
        uses: actions/checkout@v3

      - name: NCTL Docker Image Exists
        if: ${{ steps.nctl-docker-image-exists.outputs.tag == 'found' }}
        run: | 
          echo "Using docker.io image...${{ github.event.inputs.node-version }}"         
          docker run --rm -it --name cspr-nctl -d -p 25101:25101 -p 11101:11101 -p 14101:14101 -p 18101:18101 stormeye2000/cspr-nctl:${{ github.event.inputs.node-version }}


      - name: NCTL Docker Image Doesn't Exist
        if: ${{ steps.nctl-docker-image-exists.outputs.tag != 'found' }}
        run: |
          echo "Building docker image...${{ github.event.inputs.node-version }}"
          docker build --build-arg="GITBRANCH=${{ github.event.inputs.node-version }}" -t stormeye2000/cspr-nctl .
          docker run --rm -it --name cspr-nctl -d -p 25101:25101 -p 11101:11101 -p 14101:14101 -p 18101:18101 stormeye2000/cspr-nctl

  workflow:

    if: ${{github.event.inputs.run-java-tests == 'true'}}
    needs: build
    name: Java SDK Tests
    uses: ./.github/workflows/action.yml
    with:
        java-repo: ${{ github.event.inputs.java-repo }}
